### ISSUE TITLE
Admin frontend macht komische Sachen bei mir

### ISSUE THREAD

**Issue by DerErli** [m4rl0ne/klostermaps-frontend#15]
![weird_sizing](https://user-images.githubusercontent.com/40774434/76449615-b5a21d00-63cc-11ea-867c-df6299e114c1.png)

**Comment by DerErli** [comment]
Das ist ohne scrollen und so

**Comment by m4rl0ne** [comment]
Was genau ist daran komisch? :D

**Comment by m4rl0ne** [comment]
Achso dass es links und rechts abgeschnitten ist?

**Comment by DerErli** [comment]
jup

**Comment by DerErli** [comment]
manchmal tauchen auch marker nicht ganz auf oder menüs sind zu groß, ich glaube das liegt an firefox
